version: '3'
services:
  app:
    ports:
      - "8000:80"
    build: ./docker/app
    container_name: php_app
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_db
      MYSQL_USER: php_user
      MYSQL_PASSWORD: php_pass
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf    
    ports:
      - 3306:3306
